var msg = "Welcome to TypeScript";
console.log(msg);
var x = 100;
console.log("X value is " + x);
var y = 12.45;
console.log("Y value is " + y);
var str = "TypeSript";
console.log("String value is " + str);
var b = true;
console.log("Boolean value is " + b);
var n = 5678;
console.log("Any Data Type value is " + n);
